### ISSUE TITLE
KeyError (line 14)

### ISSUE THREAD

**Issue by Limbicnation** [antiboredom/flickr-scrape#1]
I get an "KeyError" after inserting my flickr api key and running the script.

**Comment by antiboredom** [comment]
Apologies - this isn't documented anywhere. You actually need to create a new file in the same directory as `scraper.py` called `credentials.json`. Inside this file you need to put a flickr api key and secret key, just like so:

```json
{
  "KEY": "your_flickr_key_here",
  "SECRET": "your_secret_key_here"
}
```

To get a key/secret you need to sign up for flickr api here: https://www.flickr.com/services/api/keys/

Let me know if this works for you.

**Comment by Limbicnation** [comment]
Hi thanks for the quick reply. I've created a json file with my KEY. However I do get an error after running. "KEYError"
The same KEY and SECRET I've added to the scraper.py file. Line 14,15. If I don't insert anything there, it won't work.

**Comment by antiboredom** [comment]
it's hard for me to debug without seeing the files. If you feel comfortable, feel free to email them to me at lavigne@saaaam.com
