### ISSUE TITLE
error with line 7, in <module>

### ISSUE THREAD

**Issue by plaidam** [antiboredom/flickr-scrape#6]
Any idea why I'm getting this error?

Traceback (most recent call last):
  File "scraper.py", line 7, in <module>
    import requests

Thanks

**Comment by ariefwicaksono08** [comment]
pip install requests

**Comment by OTH-arch** [comment]
hey I have the same error @plaidam and "pip install requests" did also not work (already satisfied) are there someone who could please help? 
thanks

**Comment by antiboredom** [comment]
Hi @OTH-arch - depending on your system you may have multiple versions of pip and python. You may need to either install using `pip3` and/or run the script using `python3`.
