### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by kimxxx333** [antiboredom/flickr-scrape#8]
Hello,
I created the credential.json file with my credentials, but after running the scraper, I received this error: 
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 9 (char 8)

Could anyone help me with this? Thanks!

**Comment by antiboredom** [comment]
I think you might have an error in your json file. Make sure that there is a comma at the end of the first line!
